server:
  port: 8280

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?characterEncoding=utf-8
    username: root
    password: root

  cache:
    type: REDIS
    redis:
      cache-null-values: false
      time-to-live: 600000ms
      use-key-prefix: true
    cache-names: userCache,allUsersCache
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
graphiql:
  enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG

#整合rabbitmq
rabbitmq:
  host: localhost
  ##服务器端口
  port: 5672
  virtual-host: /
  username: guest
  password: guest
  publisher-confirms: true #如果对异步消息需要回调必须设置为true
